### ISSUE TITLE
v 1.9.8 NullPointerException Issue

### ISSUE THREAD

**Issue by TUCAOEVER** [Cutiemango/MangoQuest#6]
Plugins (16): Citizens, Essentials,  (WorldEdit)FastAsyncWorldEdit, HolographicDisplays, HolographicPlaceholders, MangoQuest, Multiverse-Core, PlaceholderAPI, ProtocolLib, Repuska, Skript, skript-reflect*, skript-yaml, Vault, VoidGenerator, WorldEditSUI

服务器版本 1.15.2 Paper
触发条件 当设置任务所需条件时

[17:13:06 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mq' in plugin MangoQuest v1.9.8
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-391]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-391]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1869) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1677) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1106) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1099) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1060) ~[patched_1.15.2.jar:git-Paper-391]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:975) ~[patched_1.15.2.jar:git-Paper-391]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at me.Cutiemango.MangoQuest.editor.QuestEditorManager.editQuestRequirement(QuestEditorManager.java:477) ~[?:?]
        at me.Cutiemango.MangoQuest.commands.edtior.CommandEditQuest.editRequirements(CommandEditQuest.java:149) ~[?:?]
        at me.Cutiemango.MangoQuest.commands.edtior.CommandEditQuest.execute(CommandEditQuest.java:74) ~[?:?]
        at me.Cutiemango.MangoQuest.commands.QuestEditorCommand.execute(QuestEditorCommand.java:128) ~[?:?]
        at me.Cutiemango.MangoQuest.commands.CommandReceiver.onCommand(CommandReceiver.java:36) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-391]
        ... 17 more

**Comment by Cutiemango** [comment]
Thank you for reporting bugs.
This bug should be fixed in today's commit. Please download the latest version and try it out.

Friendly reminder: you can also report bugs in the [public discord](https://discord.gg/ACrURmp).
